import { readdirSync } from "node:fs";
import path from "node:path";
import { prisma } from "@/lib/db";

/**
 * Database reachability probe — deliberately SEPARATE from /api/health.
 *
 * /api/health must stay dependency-free (a DB outage must not make a healthy
 * front end look dead). This endpoint answers the different question: "can the
 * app actually talk to its database?" Login needs that, and when it broke the
 * only outward symptom was a generic "Something went wrong" on the form.
 *
 * Returns the driver's error CODE and message only — never the connection
 * string, credentials, host or any row data.
 */
export const dynamic = "force-dynamic";

export async function GET() {
  const started = Date.now();
  try {
    // Cheapest possible round-trip that proves auth + reachability + schema:
    // counting a table login depends on.
    const users = await prisma.adminUser.count();
    return Response.json(
      { ok: true, adminUsers: users, ms: Date.now() - started },
      { headers: { "Cache-Control": "no-store" } },
    );
  } catch (e: unknown) {
    const err = e as { name?: string; code?: string; errorCode?: string; message?: string };
    // Prisma puts the actual cause several lines in, after blank lines, so drop
    // the empties before trimming — an earlier version sliced the first 4 raw
    // lines and cut the real error off entirely.
    const detail = (err.message ?? "")
      .split("\n")
      .map((l) => l.trim())
      .filter(Boolean)
      .slice(0, 6)
      .join(" | ")
      .slice(0, 500);

    // Describe the configured datasource WITHOUT credentials, so a wrong host or
    // database name is visible while the password never is.
    let datasource = "unset";
    let pwFingerprint = "n/a";
    const raw = process.env.DATABASE_URL;
    if (raw) {
      try {
        const u = new URL(raw);
        datasource = `${u.protocol.replace(":", "")}://<user>:<redacted>@${u.hostname}:${u.port || "default"}${u.pathname}`;
        // A short one-way fingerprint of the configured password. This is NOT the
        // password and cannot be reversed; it exists so a stale credential can be
        // identified by comparing against known candidates offline, instead of
        // guessing which of several passwords the deployment is actually using.
        // Remove once the credential is confirmed correct.
        if (u.password) {
          pwFingerprint = require("node:crypto")
            .createHash("md5")
            .update(decodeURIComponent(u.password))
            .digest("hex")
            .slice(0, 12);
        }
      } catch {
        datasource = "set-but-unparseable";
      }
    }

    // Where does the generated Prisma client actually live at runtime, and is the
    // query-engine binary next to it? The engines are regenerated by the build
    // rather than committed, so this shows whether the deploy carried them over.
    const candidates = [
      path.join(process.cwd(), "src/generated/prisma"),
      path.join(process.cwd(), "apps/grow/src/generated/prisma"),
    ];
    const engines: Record<string, string[]> = {};
    for (const dir of candidates) {
      try {
        engines[dir] = readdirSync(dir).filter(
          (f) => f.includes("query_engine") || f.includes("query-engine") || f.endsWith(".node"),
        );
      } catch (readErr) {
        engines[dir] = [`<${(readErr as { code?: string }).code ?? "unreadable"}>`];
      }
    }

    return Response.json(
      {
        ok: false,
        ms: Date.now() - started,
        name: err.name ?? "unknown",
        code: err.code ?? err.errorCode ?? "unknown",
        datasource,
        pwFingerprint,
        envSource: process.env.DATABASE_URL ? "process-env" : "absent",
        cwd: process.cwd(),
        engines,
        message: detail,
      },
      { status: 503, headers: { "Cache-Control": "no-store" } },
    );
  }
}
